/*
 * generated by Xtext
 */
package br.ufmg.dcc.asml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import br.ufmg.dcc.asml.ui.syntaxcoloring.ASMLSemanticHighlightingCalculator;
import br.ufmg.dcc.asml.ui.syntaxcoloring.ASMLSemanticHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ASMLModelUiModule extends
		br.ufmg.dcc.asml.ui.AbstractASMLModelUiModule {
	public ASMLModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return ASMLSemanticHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return  ASMLSemanticHighlightingCalculator.class;
	}
}
