/*
 * generated by Xtext
 */
package br.ufmg.dcc.asml;

import org.eclipse.xtext.formatting.IFormatter;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

import br.ufmg.dcc.asml.formatting.ASMLModelFormatter;
import br.ufmg.dcc.asml.scoping.ASMLImportUriGlobalScopeProvider;


/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class ASMLModelRuntimeModule extends br.ufmg.dcc.asml.AbstractASMLModelRuntimeModule {
/*	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return super.bindIGlobalScopeProvider();
	}*/
	
/*	@Override
	public void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).
		  annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(ASMLImportUriGlobalScopeProvider.class);	
	}
	*/
	
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return ASMLImportUriGlobalScopeProvider.class;
	}
	
	@Override
	public Class<? extends IFormatter> bindIFormatter() {
		return ASMLModelFormatter.class;
	}
}
