/*
* generated by Xtext
*/
package br.ufmg.dcc.asml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ASMLModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("br/ufmg/dcc/asml/parser/antlr/internal/InternalASMLModel.tokens");
	}
}
