/*
* generated by Xtext
*/
package br.ufmg.dcc.asml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.ufmg.dcc.asml.services.ASMLModelGrammarAccess;

public class ASMLModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ASMLModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.ufmg.dcc.asml.parser.antlr.internal.InternalASMLModelParser createParser(XtextTokenStream stream) {
		return new br.ufmg.dcc.asml.parser.antlr.internal.InternalASMLModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ASMLModel";
	}
	
	public ASMLModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ASMLModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
