/*
* generated by Xtext
*/
package br.ufmg.dcc.asml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ASMLModelStandaloneSetup extends ASMLModelStandaloneSetupGenerated{

	public static void doSetup() {
		new ASMLModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

